[package]
name = "lung"
version = "0.0.1-dev"
edition = "2024"

[dependencies]
aes-gcm = "0.10.3"
chacha20poly1305 = "0.10.1"
ed25519-compact = "2.1.1"
hkdf = "0.12.4"
rand = "0.9.2"
sha2 = "0.10.9"
x25519-dalek = { version = "2.0.1", features = ["static_secrets"] }
